<?php

/**
 * This is the model base class for the table "lep_event".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "LepEvent".
 *
 * Columns in table "lep_event" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $event_id
 * @property integer $res_id
 * @property integer $user_id
 * @property string $title
 * @property string $event
 * @property string $date
 * @property string $status
 * @property string $created_at
 *
 */
abstract class BaseLepEvent extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'lep_event';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'LepEvent|LepEvents', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('res_id, user_id', 'numerical', 'integerOnly'=>true),
			array('title', 'length', 'max'=>255),
			array('date, created_at', 'length', 'max'=>10),
			array('status', 'length', 'max'=>1),
			array('event', 'safe'),
			array('res_id, user_id, title, event, date, status, created_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('event_id, res_id, user_id, title, event, date, status, created_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'event_id' => Yii::t('app', 'Event'),
			'res_id' => Yii::t('app', 'Res'),
			'user_id' => Yii::t('app', 'User'),
			'title' => Yii::t('app', 'Title'),
			'event' => Yii::t('app', 'Event'),
			'date' => Yii::t('app', 'Date'),
			'status' => Yii::t('app', 'Status'),
			'created_at' => Yii::t('app', 'Created At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('event_id', $this->event_id);
		$criteria->compare('res_id', $this->res_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('event', $this->event, true);
		$criteria->compare('date', $this->date, true);
		$criteria->compare('status', $this->status, true);
		$criteria->compare('created_at', $this->created_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}