<?php

/**
 * This is the model base class for the table "lep_promo".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "LepPromo".
 *
 * Columns in table "lep_promo" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $promo_id
 * @property integer $res_id
 * @property integer $user_id
 * @property string $promo
 * @property string $status
 * @property string $created_at
 *
 */
abstract class BaseLepPromo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'lep_promo';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'LepPromo|LepPromos', $n);
	}

	public static function representingColumn() {
		return 'promo';
	}

	public function rules() {
		return array(
			array('res_id, user_id', 'numerical', 'integerOnly'=>true),
			array('status', 'length', 'max'=>1),
			array('created_at', 'length', 'max'=>10),
			array('promo', 'safe'),
			array('res_id, user_id, promo, status, created_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('promo_id, res_id, user_id, promo, status, created_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'promo_id' => Yii::t('app', 'Promo'),
			'res_id' => Yii::t('app', 'Res'),
			'user_id' => Yii::t('app', 'User'),
			'promo' => Yii::t('app', 'Promo'),
			'status' => Yii::t('app', 'Status'),
			'created_at' => Yii::t('app', 'Created At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('promo_id', $this->promo_id);
		$criteria->compare('res_id', $this->res_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('promo', $this->promo, true);
		$criteria->compare('status', $this->status, true);
		$criteria->compare('created_at', $this->created_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}