<?php

/**
 * This is the model base class for the table "lep_product".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "LepProduct".
 *
 * Columns in table "lep_product" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $product_id
 * @property integer $res_id
 * @property integer $user_id
 * @property integer $prod_cat_id
 * @property string $title
 * @property string $description
 * @property string $image
 * @property string $price
 * @property string $status
 * @property string $created_at
 *
 */
abstract class BaseLepProduct extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'lep_product';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'LepProduct|LepProducts', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('prod_cat_id', 'required'),
			array('res_id, user_id, prod_cat_id', 'numerical', 'integerOnly'=>true),
			array('title, image, price', 'length', 'max'=>255),
			array('status', 'length', 'max'=>1),
			array('created_at', 'length', 'max'=>10),
			array('description', 'safe'),
			array('res_id, user_id, title, description, image, price, status, created_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('product_id, res_id, user_id, prod_cat_id, title, description, image, price, status, created_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'product_id' => Yii::t('app', 'Product'),
			'res_id' => Yii::t('app', 'Res'),
			'user_id' => Yii::t('app', 'User'),
			'prod_cat_id' => Yii::t('app', 'Prod Cat'),
			'title' => Yii::t('app', 'Title'),
			'description' => Yii::t('app', 'Description'),
			'image' => Yii::t('app', 'Image'),
			'price' => Yii::t('app', 'Price'),
			'status' => Yii::t('app', 'Status'),
			'created_at' => Yii::t('app', 'Created At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('product_id', $this->product_id);
		$criteria->compare('res_id', $this->res_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('prod_cat_id', $this->prod_cat_id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('image', $this->image, true);
		$criteria->compare('price', $this->price, true);
		$criteria->compare('status', $this->status, true);
		$criteria->compare('created_at', $this->created_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}