<?php

/**
 * This is the model base class for the table "lep_banner".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "LepBanner".
 *
 * Columns in table "lep_banner" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $banner_id
 * @property string $expire
 * @property string $code
 * @property string $image
 * @property string $url
 * @property string $new_window
 * @property string $position
 * @property integer $order_num
 * @property string $reminder1
 * @property string $reminder2
 * @property string $reminder3
 *
 */
abstract class BaseLepBanner extends GxActiveRecord {

    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'lep_banner';
    }

    public static function label($n = 1) {
        return Yii::t('app', 'LepBanner|LepBanners', $n);
    }

    public static function representingColumn() {
        return 'expire';
    }

    public function rules() {
        return array(
            array('order_num', 'numerical', 'integerOnly' => true),
            array('expire, image, url, position', 'length', 'max' => 255),
            array('new_window, reminder1, reminder2, reminder3', 'length', 'max' => 1),
            array('code', 'safe'),
            array('expire, code, image, url, new_window, position, order_num, reminder1, reminder2, reminder3', 'default', 'setOnEmpty' => true, 'value' => null),
            array('banner_id, expire, code, image, url, new_window, position, order_num, reminder1, reminder2, reminder3', 'safe', 'on' => 'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    public function pivotModels() {
        return array(
        );
    }

    public function attributeLabels() {
        return array(
            'banner_id' => Yii::t('app', 'Banner'),
            'expire' => Yii::t('app', 'Expire'),
            'code' => Yii::t('app', 'Code'),
            'image' => Yii::t('app', 'Image'),
            'url' => Yii::t('app', 'Url'),
            'new_window' => Yii::t('app', 'New Window'),
            'position' => Yii::t('app', 'Position'),
            'order_num' => Yii::t('app', 'Order Num'),
            'reminder1' => Yii::t('app', 'Reminder1'),
            'reminder2' => Yii::t('app', 'Reminder2'),
            'reminder3' => Yii::t('app', 'Reminder3'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('banner_id', $this->banner_id);
        $criteria->compare('expire', $this->expire, true);
        $criteria->compare('code', $this->code, true);
        $criteria->compare('image', $this->image, true);
        $criteria->compare('url', $this->url, true);
        $criteria->compare('new_window', $this->new_window, true);
        $criteria->compare('position', $this->position, true);
        $criteria->compare('order_num', $this->order_num);
        $criteria->compare('reminder1', $this->reminder1, true);
        $criteria->compare('reminder2', $this->reminder2, true);
        $criteria->compare('reminder3', $this->reminder3, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function indexBanner() {
        $sql = "
            SELECT banner_id, image FROM lep_banner limit 5
        ";
        $connection = Yii::app()->db;
        $command = $connection->createCommand($sql);
        $row = $command->queryAll();
        return $row;
    }

}